### ISSUE TITLE
Could not retrieve rustic-doc-convert.sh

### ISSUE THREAD

**Issue by parvizfarnia** [brotzeit/rustic#208]
I've the following in my emacs init:

```
;; =============================
;; Requried packages to install
;; =============================
;; sudo apt install pandoc
;; M-x package-install RET lsp-mode RET
;; M-x package-install RET rustic RET
;; M-x package-install helm-ag
;; M-x package-install RET gnu-elpa-keyring-update RET
;;
(require 'lsp-mode)
(use-package rustic)
(add-hook 'rustic-mode-hook
      (lambda () (setq indent-tabs-mode nil)))
(setq rustic-lsp-server 'rls)
```

I was reading the [inline documentation](https://github.com/brotzeit/rustic#inline-documentation) section in the installation guide. I proceeded exactly as indicated that is:

- I run `M-x rustic-doc-mode`
When I run this Emacs printed the following message in the message bar: `Rustic-Doc mode enabled in the current buffer`

- But when I run the second instruction: `M-x rustic-doc-setup` I got the following error message:
`Could not retrieve /home/myuser/.local/bin/rustic-doc-convert.sh`

I searched in the file system and Indeed I wasn't able to find this script. Is this a bug or it's my rustic installation which is broken?

My environment:
```
OS: Ubuntu 20.04 (64 bits)
Emacs: 27.1
```

**Comment by parvizfarnia** [comment]
I managed to solve the first problem. I had not a **bin** directory in **~/.local** and apparently the program doesn't check whether the bin directory already exists. So I created the directory manually and after running again, this initial issue was solved. But then I encountered other problems upon installing the required dependencies. Indeed here is what we can find in `rustic-doc.el`:

```
(defun rustic-doc-install-deps ()
  "Install dependencies with Cargo."
  (if (not (executable-find "cargo"))
      (message "You need to have cargo installed to use rustic-doc")
    (let ((missing-rg (not (executable-find "rg")))
          (missing-fd (not (executable-find "fd")))
          (missing-makedocs (not (executable-find "cargo-makedocs"))))
      (when (and  (or missing-fd missing-makedocs missing-rg) (y-or-n-p "Missing some dependencies for rustic doc, install them? "))
        (when missing-fd
          (rustic-doc--start-process "install-fd" "cargo" nil "install" "fd-find"))
        (when missing-rg
          (rustic-doc--start-process "install-rg" "cargo" nil "install" "ripgrep"))
        (when missing-makedocs
          (rustic-doc--start-process "install-makedocs" "cargo" nil "install" "cargo-makedocs"))))))
```

When this function is called I get the following error message:

`error in process sentinel Wrong number of arguments`

I checked the list of prerequisites that this function seeks to install and I observed that only **fd-find** and **ripgrep** were absent on my system so I installed them manuelly:

```
sudo apt install ripgrep
sudo apt install fd-find
```

This solved the problem with `rustic-doc-install-deps ()`. Then I saw the following message in Emacs message bar

`Setup is converting the standard library`

During several minutes this message was fix in Emacs message bar and I had the feeling that the program was doing something in background. Finally after a few minutes I got the following error message:

`error in process sentinel: Wrong number of arguments: (1 . 1), 2 [2 times]`

I checkd the `*rustid-doc-std-conversion*` buffer in Emacs to see more details and here is the message error that I found:


```
Error running filter /home/myuser/.local/bin/rustic-doc-filter.lua:
Error during function call: /home/myuser/.local/bin/rustic-doc-filter.lua:103: attempt to index a nil value (field 'List')
stack traceback:
	/home/myuser/.local/bin/rustic-doc-filter.lua:103: in function </home/myuser/.local/bin/rustic-doc-filter.lua:45>
	[C]: in ?
	[C]: in function 'pandoc.walk_block'
	/home/myuser/.local/bin/rustic-doc-filter.lua:153: in function 'Pandoc'
stack traceback:
	[C]: in function 'pandoc.walk_block'
	/home/myuser/.local/bin/rustic-doc-filter.lua:153: in function 'Pandoc'

```
Unfortunately I wasn't able to advance more.

**Comment by samhedin** [comment]
Thank you for the detailed and persistent report. What version of pandoc are you using?

**Comment by parvizfarnia** [comment]
Thanks and happy new year.

Here is the information about pandoc:

```
$ pandoc --version
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
Default user data directory: /home/myuser/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
$ 

```

**Comment by samhedin** [comment]
Could you try the PR and see if it solves your issue with the bin directory, and the one with dependencies failing to install? As far as the pandoc issue is concerned, could you try a more recent version? I just ran on 2.11 and it worked fine.

**Comment by parvizfarnia** [comment]
I confirm that `~/.local/bin` exists (as explained earlier I had to create it manually). Following your advice I downloaded and installed the most recent version of `pandoc`

```
$ wget https://github.com/jgm/pandoc/releases/download/2.11.3.2/pandoc-2.11.3.2-1-amd64.deb
$
$ dpkg -i pandoc-2.11.3.2-1-amd64.deb
$
$ pandoc --version
pandoc 2.11.3.2
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.3, ipynb 0.1.0.1
User data directory: /home/myuser/.local/share/pandoc or /home/myuser/.pandoc
Copyright (C) 2006-2020 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
$

```
So after this, what I did was to rerun the `rustic-doc-setup` command. After a few minutes I got once again the same error message

`error in process sentinel: Wrong number of arguments: (1 . 1), 2 [2 times]`

But this time the situation was completely different. As I indicated in my previous post, there was an error message in the buffer named: `*rustid-doc-std-conversion*`  (`... Error during function call: /home/myuser/.local/bin/rustic-doc-filter.lua:103: attempt to index a nil valu ...`). After installing the most recent version of pandoc I didn't get this error message anymore and this time there was only one line in the buffer:

`Generating org files in: /home/myuser/.local/share/emacs/rustic-doc/std`

I checked the content of this directory and indeed there were a lot of .org files and directories:

```
$ ls /home/myuser/.local/share/emacs/rustic-doc/std
alloc        hint                  keyword.for.org     keyword.where.org          macro.include_bytes.org                  macro.unimplemented.org  prim_i16                 primitive.u128.org   result
all.org      i128                  keyword.if.org      keyword.while.org          macro.include.org                        macro.unreachable.org    prim_i32                 primitive.u16.org    slice
any          i16                   keyword.impl.org    lazy                       macro.include_str.org                    macro.vec.org            prim_i64                 primitive.u32.org    str
array        i32                   keyword.in.org      macro.asm.org              macro.is_aarch64_feature_detected.org    macro.writeln.org        prim_i8                  primitive.u64.org    string
ascii        i64                   keyword.let.org     macro.assert_eq.org        macro.is_arm_feature_detected.org        macro.write.org          prim_isize               primitive.u8.org     sync
backtrace    i8                    keyword.loop.org    macro.assert_ne.org        macro.is_mips64_feature_detected.org     marker                   primitive                primitive.unit.org   sys
borrow       index.org             keyword.match.org   macro.assert.org           macro.is_mips_feature_detected.org       mem                      primitive.array.org      primitive.usize.org  sys_common
boxed        intrinsics            keyword.mod.org     macro.cfg.org              macro.is_powerpc64_feature_detected.org  net                      primitive.bool.org       prim_never           task
cell         io                    keyword.move.org    macro.column.org           macro.is_powerpc_feature_detected.org    num                      primitive.char.org       prim_pointer         thread
char         isize                 keyword.mut.org     macro.compile_error.org    macro.is_x86_feature_detected.org        ops                      primitive.f32.org        prim_ref             time
clone        iter                  keyword.pub.org     macro.concat_idents.org    macro.line.org                           option                   primitive.f64.org        prim_slice           u128
cmp          keyword.as.org        keyword.ref.org     macro.concat.org           macro.llvm_asm.org                       os                       primitive.fn.org         prim_str             u16
collections  keyword.async.org     keyword.return.org  macro.dbg.org              macro.log_syntax.org                     panic                    primitive.i128.org       prim_tuple           u32
convert      keyword.await.org     keyword.self.org    macro.debug_assert_eq.org  macro.matches.org                        panicking                primitive.i16.org        prim_u128            u64
default      keyword.break.org     keyword.Self.org    macro.debug_assert_ne.org  macro.module_path.org                    path                     primitive.i32.org        prim_u16             u8
env          keyword.const.org     keyword.static.org  macro.debug_assert.org     macro.option_env.org                     pin                      primitive.i64.org        prim_u32             usize
error        keyword.continue.org  keyword.struct.org  macro.env.org              macro.panic.org                          prelude                  primitive.i8.org         prim_u64             vec
f32          keyword.crate.org     keyword.super.org   macro.eprintln.org         macro.println.org                        prim_array               primitive.isize.org      prim_u8
f64          keyword.dyn.org       keyword.trait.org   macro.eprint.org           macro.print.org                          prim_bool                primitive.never.org      prim_unit
ffi          keyword.else.org      keyword.true.org    macro.file.org             macro.stringify.org                      prim_char                primitive.pointer.org    prim_usize
fmt          keyword.enum.org      keyword.type.org    macro.format_args_nl.org   macro.thread_local.org                   prim_f32                 primitive.reference.org  process
fs           keyword.extern.org    keyword.union.org   macro.format_args.org      macro.todo.org                           prim_f64                 primitive.slice.org      ptr
future       keyword.false.org     keyword.unsafe.org  macro.format.org           macro.trace_macros.org                   prim_fn                  primitive.str.org        raw
hash         keyword.fn.org        keyword.use.org     macro.global_asm.org       macro.try.org                            prim_i128                primitive.tuple.org      rc
```



I opened a Rust program buffer and I did `C-#` and I entered `panic` as keyword just to see whether the related documentation was available. Good news! I got a beautiful org mode documentation! I repeated the process with several other key words such as, `Option, for, else, let, etc.` and each time I was able to view the documentation (well formatted with nice syntax highlighting).

Consequently, thanks to your suggestion about installing a more recent version of pandoc I was able to view the documentation inside Emacs. Now about the above mentioned error message, that is:

`error in process sentinel: Wrong number of arguments: (1 . 1), 2 [2 times]`

I have no explanation, does this mean that somewhat the process of installing/converting the documentation failed in the middle or not? I've no Idea.

Should I close this issue?

**Comment by samhedin** [comment]
Good to hear that you got it working! I believe that the error in process sentinel is not because of some issue with the conversion, rather it was just a minor issue where a function was called with one instead of two arguments. That should be fixed as of the PR. Furthermore, we now confirm that the .local/bin exists and create it if not.

So if everything is fine, this should be ready to close.

**Comment by parvizfarnia** [comment]
Many thanks for your time and for your help and once again Happy new year 2021!

**Comment by parvizfarnia** [comment]
Hi, I created this thread in 2021 under Linux. Based on the above information provided the issue was resolved on Linux. But I have now a new version of Emacs (28.1) installed on Windows 11 (64 bits) and I can confirm the above-mentioned problems persist :

- One has to create manually the `/.local/bin` directory in users' home directory
Otherwise the program gives the following error message:
`Could not retrieve c:/Users/myusername/AppData/Roaming/.local/bin/rustic-doc-convert.sh`

- I downloaded the binary of the most recent version of `pandoc` for Windows (64 bits), yet after running `rustic-doc-set-up` I get the following error message in `*Messages*` buffer in emacs
```
Contacting host: raw.githubusercontent.com:443
Wrote c:/Users/myusername/AppData/Roaming/.local/bin/rustic-doc-convert.sh
Contacting host: raw.githubusercontent.com:443
Wrote c:/Users/myusername/AppData/Roaming/.local/bin/rustic-doc-filter.lua
start-process: Spawning child process: Invalid argument
Loading c:/Users/myusername/AppData/Roaming/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
```

Am I missing something?

**Comment by samhedin** [comment]
Hey! I have not considered how `rustic-doc` works on windows. I just tried installing it again on Linux and it works.
Do you get a buffer called `*rustic-doc-std-conversion*` when you run setup? If so, what does that say?

**Comment by parvizfarnia** [comment]
Thanks for your reply. Yes there is a buffer named `*rustic-doc-std-conversion*` but it is completely empty (after running setup). So basically `rustic-doc` is not for Windows, right?

**Comment by samhedin** [comment]
I would love for it to work on Windows. Unfortunately, I don't know what would be required.
Pandoc and fd-find both exist for windows. My guess is that the file paths and `convert.sh/rustic-doc-convert.sh` are the places to start to support Windows.

**Comment by parvizfarnia** [comment]
Ok, I see. Thanks for this information. The reason that I tried also on Windows is because I didn't see any specific note on rustic page on Github indicating that rustic-doc isn't compatible with Windows. But now it seems that there adaptations to be done. It's good that now it's clear and others who may have encountered the same problem might read the information in this thread. Thanks for your help.

**Comment by samhedin** [comment]
This should be in the documentation, it just never crossed my mind. I'll update the docs.
